### ISSUE TITLE
Agrona Snapshot 3.2 Not Released.

### ISSUE THREAD

**Issue by edwardbeckett** [tmontgomery/Amaethon#1]
Unmet dependency for `uk.co.real-logic:Agrona:0.3.2-SNAPSHOT` ~ SNAP not committed. ~ `https://github.com/real-logic/Agrona/tree/0.3.1`

**Comment by mjpt777** [comment]
I've updated the project and it now builds with the Maven published dependencies.

**Comment by edwardbeckett** [comment]
+1 Thank you sir ;)
